### ISSUE TITLE
Tests in NLsolve now fail.

### ISSUE THREAD

**Issue by KristofferC** [anriseth/LineSearches.jl#24]
Hello, tests in NLsolve now fail (since 1-2 months ago) when upgrading some deps and fixing some deprecation warnings. https://github.com/EconForge/NLsolve.jl. The tests uses `backtracking!` so has there been any changes to the `backtracking!` line search that could cuase the tests to fail?

**Comment by anriseth** [comment]
'v0.1.3' includes large changes in `backtracking!` #20. The standard backtracking algorithm has been replaced by backtracking with a choice of quadratic and cubic (default) interpolation. This should improve the performance, but let me know if it hasn't. 

Maybe we should include some `NLSolve` tests in LineSearches, to ensure default settings don't break anything?

In case you don't do this already: For Newton, and potentially quasi-Newton, methods with backtracking, I would also recommend starting each linesearch with an initial step length of 1.0. See benchmarks in JuliaOpt/Optim.jl#328.

**Comment by anriseth** [comment]
There were also some changes in #7 a while back that might have changed default behaviour slightly.

**Comment by KristofferC** [comment]
I had some time for this now. I rolled back to pretty much the first commit here and then things passed. I then bisected and tests starts to fail after #7.

**Comment by anriseth** [comment]
I see, so there must have been some small changes to default behaviour in
#7. ( @cortner ?)

@KristofferC What are the NLsolve commit and tests you are running this on?

I'm away from a computer until January 11, so I won't be able to look at
this until then.

**Comment by cortner** [comment]
#7 should not have changed default behaviour. Though who knows, is there a small code snippet to experiment with?

**Comment by pkofod** [comment]
Everything new in #7 is encapsulated in control flow statements that defaults to not having their conditions met, so I can't see how that would change default behaviour...

**Comment by pkofod** [comment]
No, wait.. It must be https://github.com/anriseth/LineSearches.jl/pull/7/files#diff-a87ded06ea9adebda2a7ec97b4005729R89 and the line below then.

**Comment by KristofferC** [comment]
Yeah, perhaps we are using it wrong now after that change.

**Comment by KristofferC** [comment]
I found the bug (in NLsolve) https://github.com/EconForge/NLsolve.jl/pull/81

**Comment by KristofferC** [comment]
Bisecting again, tests now fail at https://github.com/anriseth/LineSearches.jl/pull/20. I will give a working example.

**Comment by anriseth** [comment]
Have you tried ’bt2!’ ? It could be that the new, default backtracking
approach (bt3!) which uses cubic interpolation is not appropriate for this
function.

Also: how is the initial line step size set for Newton in NLsolve?
Backtracking usually performs best when the initial step size is 1.0 for
each Newton direction.

**Comment by KristofferC** [comment]
It is set to one. I will try the other function.

**Comment by KristofferC** [comment]
The other linesearches did not work well either.  I changed nlsolve to not use linesearches in the tests since I do not have much time to look into this.

**Comment by anriseth** [comment]
I'll reopen this, as we should have a "basic" linesearch that just performs the step in the search direction anyway. 
I worked on nonlinear systems arising from PDEs in 2015, and got the best performance using this method. 
Ref #25

**Comment by anriseth** [comment]
@KristofferC, you can use the `basic!` linesearch added in v0.1.4 (waiting for https://github.com/JuliaLang/METADATA.jl/pull/7568 ). In case that makes things easier in the future than disabling linesearches.
