### ISSUE TITLE
Create basic linesearch with predefined step-length

### ISSUE THREAD

**Issue by anriseth** [anriseth/LineSearches.jl#25]
Can be useful for example with Newton's method in the quadratic regime.

Similar to 
https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESLINESEARCHBASIC.html

This should also help #24

**Comment by pkofod** [comment]
Aka "learning parameter" in ml, right?

**Comment by anriseth** [comment]
I don't know the ML lingo, but I basically means that, given a search direction, we just take the step ("damped" by some alpha given as a parameter, default = 1.0). See #26.

**Comment by pkofod** [comment]
Yes, a fixed step size. Good idea.
