### ISSUE TITLE
Incompatible arguments

### ISSUE THREAD

**Issue by cortner** [anriseth/LineSearches.jl#4]
If I try to use `LineSearches.hz_linesearch!` instead of `Optim.hz_linesearch!` then I get the following error: 

```
LoadError: MethodError: no method matching hz_linesearch!(::Optim.DifferentiableFunction, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Optim.LineSearchResults{Float64}, ::Float64, ::Bool)
Closest candidates are:
  hz_linesearch!{T}(!Matched::LineSearches.AbstractDifferentiableFunction, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, !Matched::LineSearches.LineSearchResults{T}, ::Real, ::Bool) at /Users/ortner/.julia/v0.5/LineSearches/src/hz_linesearch.jl:75
```

Is there maybe a specific branch of `Optim` that I should use?

**Comment by anriseth** [comment]
Yeah, we need to merge JuliaOpt/Optim.jl#277 first, which makes `Optim.DifferentiableFunction` a subtype of `AbstractDifferentiableFunction`

**Comment by cortner** [comment]
ok, thanks - I'll wait for that.

**Comment by anriseth** [comment]
@cortner I have removed the type signature requirement for `df`, after feedback from @pkofod in JuliaOpt/Optim.jl#277.
You should be able to use the linesearch algorithms as before, with Optim's `DifferentiableFunction` types on v0.0.2

**Comment by cortner** [comment]
not only `df` was the problem, but `LineSearchResults` as well; because there are now two versions, one in `Optim` and one in `LineSearches`. 

For now I am just hacking the old `Optim` and will incorporate any changes into `LineSearches` when it is ready.

**Comment by cortner** [comment]
Does #5 resolve this for me? or is the `LineSearchResults` still a problem?

**Comment by cortner** [comment]
Come to think of it, should I just switch to your pull-request Optim.jl #277 if I want to make changes to `LineSearches.jl`?

**Comment by anriseth** [comment]
I think `LineSearchResults` is still a problem, yes. 
The changes in JuliaOpt/Optim.jl#277 should not alter any other functionality, so you should be fine just using that.

**Comment by pkofod** [comment]
Sorry, can you remind me of the `LineSearchResults` problem?

**Comment by anriseth** [comment]
@pkofod I moved the `LineSearchResults` type from Optim.jl to LineSearches.jl.
So on `Optim` master, `Optim.LineSearchResults` is used, whilst `LineSearches` requires `LineSearches.LineSerachResults` as input type for some of the functions.

**Comment by cortner** [comment]
thanks - then maybe that is what I will do to merge my changes.

**Comment by pkofod** [comment]
Ah, perfect. Then the "problem" is just a matter of your PR in Optim not being merged yet, correct?

**Comment by anriseth** [comment]
That's correct @pkofod

**Comment by anriseth** [comment]
This should work on Optim master now.
